name: zarr-pyramid
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - boto3
  - dask
  - fsspec
  - ndpyramid
  - rasterio
  - requests
  - rioxarray
  - s3fs
  - xarray
  - zarr<3
  - aiohttp
