name: zarr-pyramid
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - boto3
  - dask
  - fsspec
  - numpy=1.23.*
  - rasterio
  - rioxarray
  - s3fs
  - xarray>=2023.1,<2024.0
  - zarr<3
  - pip:
      - ndpyramid
